# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continous integration

on:
  pull_request:
    branches: [main]

jobs:
  # Run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      storybook: ${{ steps.filter.outputs.storybook }}
      allChanges: ${{ steps.filter.outputs.allChanges }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            storybook: &storybook
              - '.storybook/**'
              - 'stories/**'
              - '**.stories.js'
              - 'package.json'
              - 'yarn.lock'
              - 'postcss.config.js'
            allChanges:
            - '**'

  test-changes-only:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'yarn test:ci'
          changes-only: true

  build-and-export-static-pages:
    needs: test-changes-only
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn run build
        env:
          NEXT_PUBLIC_BASE_PATH: /kodeworks.no-poc
      - run: yarn run export
        env:
          NEXT_PUBLIC_BASE_PATH: /kodeworks.no-poc

  build-storybook:
    needs: [changes, test-changes-only]
    if: ${{ needs.changes.outputs.storybook == 'true' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn run build-storybook
        env:
          NEXT_PUBLIC_BASE_PATH: /kodeworks.no-poc
