name: Continous integration

on:
  pull_request:
    branches: [main]

jobs:
  change-detection:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      storybook: ${{ steps.filter.outputs.storybook }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - name: Run change detection
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            storybook:
              - '.storybook/**'
              - 'stories/**'
              - 'components/**'
              - '**.stories.js'
              - 'package.json'
              - 'yarn.lock'
              - 'postcss.config.js'

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test:ci
      - uses: actions/upload-artifact@v2 # upload test results for test-report.yml
        if: always() # run this step even if previous step failed
        with:
          name: test-results
          path: reports/jest-junit.xml

  build-and-export-static-pages:
    needs: [tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn run build
        env:
          NEXT_PUBLIC_BASE_PATH: /kodeworks.no-poc
      - run: yarn run export
        env:
          NEXT_PUBLIC_BASE_PATH: /kodeworks.no-poc

  build-storybook:
    needs: [change-detection, tests]
    if: ${{ needs.change-detection.outputs.storybook == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn run build-storybook
        env:
          NEXT_PUBLIC_BASE_PATH: /kodeworks.no-poc
